### ISSUE TITLE
JE: We need feature to where we can automatically reverse the entry the next month. i.e. accruals

### ISSUE THREAD

**Issue by treywoodward** [PrimitiveSocial/MaderaPublic#110]

**Comment by jerredhurst** [comment]
Can we get a little more specifics on this?

**Comment by MaderaMike** [comment]
Often times when entering a JE we are simply wanting the expense reflected in the current month knowing that the invoice will be paid in the following month (for current month activity). In this case, we need the JE to reverse the following month meaning an exact inverse of the current JE so that they net to zero over the two months.

**Comment by mistycleb** [comment]
Validated that reverse button is there, but no way to see if it is fully functional yet
