### ISSUE TITLE
Selecting Groups of Properties

### ISSUE THREAD

**Issue by J-Anders** [PrimitiveSocial/MaderaPublic#137]
In several areas (People, Properties, Accounting, etc), you have the capability in the upper left corner of selecting which Property you want data on, or select All Properties. This feature should have the following changes:

- 

Add the option to select by region (DFW, Houston, College Station, etc) for those User roles with permission to see across regions

- 

Add the option to select by Life Cycle stage for among the Properties (have Life Cycle stages been defined yet?)

<span data-href="#aha_task_list_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

- [x] Default to a show only a given Director's Properties, based on User roles

- [x] Change to multiple select rather than radial buttons

- [ ] Add the option to select by region (DFW, Houston, College Station, etc) for those User roles with permission to see across regions

- [ ] Add the option to select by Life Cycle stage for among the Properties (have Life Cycle stages been defined yet?)
<span data-href="#aha_task_list_end" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

Aha! Link: https://primitivesocial.aha.io/features/MR-106

**Comment by jerredhurst** [comment]
**This will be implemented with user roles**
Default to a show only a given Director's Properties, based on User roles

**For Phase 1, you will be able to select all properties (which will be all that you have permission for) and the data will be aggregated or you can select a single property**
Change to multiple select rather than radial buttons

** Is there a way currently to distinguish Property by region? **

** Lifecycles have not been discussed **

**Comment by treywoodward** [comment]
Resolved.
