### ISSUE TITLE
When adding a new AP check, the check number should default and not have the ability to be changed manually.

### ISSUE THREAD

**Issue by cfjaynes** [PrimitiveSocial/MaderaPublic#20]

**Comment by jerredhurst** [comment]
@cfjaynes @madera-tray Where should the check number be determined from?  Will we start with a new check number series with the prototype?

**Comment by madera-tray** [comment]
We will use the same number sequencing form & function that is currently used in Valence.  Whenever we switch over from Valence, we will pick up from where we left off.  The majority of payables are processed through Avid so we will use the same numbering sequence as them as well.  These numbers of course are determined by Avid through the upload process so all of this will have to be tracked in the numbering logic.

Another comment from Andrew regarding manual check number change:

Except for maybe have the ability to manually change it at a certain level. Like a Dave Gilles (or Super-Admin) level so that if it ever needs to be changed, it better be our one and only option. We should also only be able to print a check once. If something happens and the check does not print, but it is already recorded in the PM software, then we must void it and reissue.
