### ISSUE TITLE
Standard Fees

### ISSUE THREAD

**Issue by J-Anders** [PrimitiveSocial/MaderaPublic#344]
Where are Standard Fees Set?  In Accounting/Accounts Receivable/Settings?  I'm looking for it but can't find it.  This would be where we set Global Standard Fee amounts for all the different types of charges.

Aha! Link: https://primitivesocial.aha.io/features/MR-4

**Comment by shawnmassie** [comment]
Click on the user image on the top right, go to property defaults, under
Accounting within there.



*From:* Jason Anders <notifications@github.com>
*Sent:* Wednesday, October 17, 2018 4:29 PM
*To:* PrimitiveSocial/MaderaPublic <MaderaPublic@noreply.github.com>
*Cc:* Subscribed <subscribed@noreply.github.com>
*Subject:* [PrimitiveSocial/MaderaPublic] Standard Fees (#344)



Where are Standard Fees Set? In Accounting/Accounts Receivable/Settings?
I'm looking for it but can't find it. This would be where we set Global
Standard Fee amounts for all the different types of charges.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/PrimitiveSocial/MaderaPublic/issues/344>, or mute the
thread

**Comment by treywoodward** [comment]
Resolved.
