### ISSUE TITLE
App not opening in Microsoft Browser

### ISSUE THREAD

**Issue by J-Anders** [PrimitiveSocial/MaderaPublic#349]
Opens correctly in Chrome, but had a user that had Microsoft as their default browser.  When clicking the link to the app, it would open to the Quote splash screen, but would hang there and not proceed to opening the app.

Aha! Link: https://primitivesocial.aha.io/features/MR-327

**Comment by treywoodward** [comment]
@J-Anders 
For the actual app, we will need to require that users utilize a modern browser, ideally chrome or firefox in order to display the components correctly. If users need a windows based browsers, we suggest them utilizing Edge (Microsoft's replacement of IE).

The Resident Portal will be able to have compatibility with IE as this will be directly facing residents.

**Comment by J-Anders** [comment]
Do you have version requirements?

**Comment by dougblackjr** [comment]
@J-Anders 
Firefox: 52+
Chrome: 57+
Edge: 17+ (really, whatever the latest is.)
Safari: 11+

IE will not support the application at all.

**Comment by mollybfisher** [comment]
closed on Nov 26, 2018 (MaderaPrivate)
