### ISSUE TITLE
When you click a building from Buildings, it takes you to a page with ALL buildings.  It should be limited to the building selected.

### ISSUE THREAD

**Issue by cfjaynes** [PrimitiveSocial/MaderaPublic#9]
<Property> -> Buildings -> <A Building>

**Comment by joshmath** [comment]
@cfjaynes "You should be able to hit back as some people may not see or use the X, this could be addressed by making the X a little more noticable. Also, if you hit escape it cause a screen error"

We don't have a back button on these type of screens because they are actually modal windows. It is not a typical best practice to have a back button on a modal, because technically the user isn't going "back" but rather just closing the modal to see the previous content. We have made it to where you can close the modal either by clicking on the "X" or hitting the escape key.
